# Generated by Django 4.2.4 on 2023-08-26 03:07

import airport_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_service', '0002_airplane'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airplane',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='airplanetype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='airplane',
            name='image',
            field=models.ImageField(null=True, upload_to=airport_service.models.airplane_image_file_path),
        ),
    ]
