# Generated by Django 4.2.4 on 2023-08-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_service', '0004_crew'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('closest_big_city', models.CharField(max_length=65)),
            ],
        ),
    ]
