# Generated by Django 4.2.4 on 2023-08-26 03:41

import airport_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_service', '0005_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='code',
            field=models.CharField(max_length=3, null=True, validators=[airport_service.models.validate_upper_case]),
        ),
    ]
