# Generated by Django 4.2.4 on 2023-08-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_service', '0008_flight_order_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='crew',
            field=models.ManyToManyField(related_name='flights', to='airport_service.crew'),
        ),
    ]
